# Permalinks
permalink:           pretty

# Setup
title:               Mark Conmy
tagline:             A Data Science Blog
url:                 http://mconmy.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Mark Conmy

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/mconmy

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
